---
version: "3.7"
services:
  backend:
    build:
      context: ./docker
    image: tcvem/backend-server:0349a7e-unsupported-hideoSuzuki
    container_name: backend
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    container_name: db
