---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tcvem
commonLabels:
  owner: tcvem
  app: backend
resources:
  # - postgres-config.yaml
  - postgres-service.yaml
  # - postgres-stateful.yaml
  - postgres-deployment.yaml
  - postgres-pv.yaml
