---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - sh
                - "-c"
                - |
                  psql -w -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
            initialDelaySeconds: 15
            timeoutSeconds: 2
