// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tcvem/backend/api/certificate.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"
import atlas_rpc "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Certficate struct {
	Id        *atlas_rpc.Identifier       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedAt *google_protobuf3.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf3.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	DeletedAt *google_protobuf3.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt" json:"deleted_at,omitempty"`
	Name      string                      `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Host      string                      `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	Port      string                      `protobuf:"bytes,7,opt,name=port" json:"port,omitempty"`
	Notes     string                      `protobuf:"bytes,8,opt,name=notes" json:"notes,omitempty"`
}

func (m *Certficate) Reset()                    { *m = Certficate{} }
func (m *Certficate) String() string            { return proto.CompactTextString(m) }
func (*Certficate) ProtoMessage()               {}
func (*Certficate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Certficate) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Certficate) GetCreatedAt() *google_protobuf3.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Certficate) GetUpdatedAt() *google_protobuf3.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Certficate) GetDeletedAt() *google_protobuf3.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *Certficate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Certficate) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Certficate) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Certficate) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type CreateCertficateRequest struct {
	Payload *Certficate `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateCertficateRequest) Reset()                    { *m = CreateCertficateRequest{} }
func (m *CreateCertficateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCertficateRequest) ProtoMessage()               {}
func (*CreateCertficateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CreateCertficateRequest) GetPayload() *Certficate {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateCertficateResponse struct {
	Result *Certficate `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreateCertficateResponse) Reset()                    { *m = CreateCertficateResponse{} }
func (m *CreateCertficateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCertficateResponse) ProtoMessage()               {}
func (*CreateCertficateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CreateCertficateResponse) GetResult() *Certficate {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadCertficateRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadCertficateRequest) Reset()                    { *m = ReadCertficateRequest{} }
func (m *ReadCertficateRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadCertficateRequest) ProtoMessage()               {}
func (*ReadCertficateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ReadCertficateRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadCertficateResponse struct {
	Result *Certficate `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadCertficateResponse) Reset()                    { *m = ReadCertficateResponse{} }
func (m *ReadCertficateResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadCertficateResponse) ProtoMessage()               {}
func (*ReadCertficateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ReadCertficateResponse) GetResult() *Certficate {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateCertficateRequest struct {
	Payload *Certficate `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateCertficateRequest) Reset()                    { *m = UpdateCertficateRequest{} }
func (m *UpdateCertficateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCertficateRequest) ProtoMessage()               {}
func (*UpdateCertficateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *UpdateCertficateRequest) GetPayload() *Certficate {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateCertficateResponse struct {
	Result *Certficate `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UpdateCertficateResponse) Reset()                    { *m = UpdateCertficateResponse{} }
func (m *UpdateCertficateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateCertficateResponse) ProtoMessage()               {}
func (*UpdateCertficateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *UpdateCertficateResponse) GetResult() *Certficate {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteCertficateRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteCertficateRequest) Reset()                    { *m = DeleteCertficateRequest{} }
func (m *DeleteCertficateRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCertficateRequest) ProtoMessage()               {}
func (*DeleteCertficateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DeleteCertficateRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteCertficateResponse struct {
}

func (m *DeleteCertficateResponse) Reset()                    { *m = DeleteCertficateResponse{} }
func (m *DeleteCertficateResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCertficateResponse) ProtoMessage()               {}
func (*DeleteCertficateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type ListCertficateRequest struct {
}

func (m *ListCertficateRequest) Reset()                    { *m = ListCertficateRequest{} }
func (m *ListCertficateRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCertficateRequest) ProtoMessage()               {}
func (*ListCertficateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type ListCertficateResponse struct {
	Results []*Certficate `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListCertficateResponse) Reset()                    { *m = ListCertficateResponse{} }
func (m *ListCertficateResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCertficateResponse) ProtoMessage()               {}
func (*ListCertficateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ListCertficateResponse) GetResults() []*Certficate {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Certficate)(nil), "certificate.Certficate")
	proto.RegisterType((*CreateCertficateRequest)(nil), "certificate.CreateCertficateRequest")
	proto.RegisterType((*CreateCertficateResponse)(nil), "certificate.CreateCertficateResponse")
	proto.RegisterType((*ReadCertficateRequest)(nil), "certificate.ReadCertficateRequest")
	proto.RegisterType((*ReadCertficateResponse)(nil), "certificate.ReadCertficateResponse")
	proto.RegisterType((*UpdateCertficateRequest)(nil), "certificate.UpdateCertficateRequest")
	proto.RegisterType((*UpdateCertficateResponse)(nil), "certificate.UpdateCertficateResponse")
	proto.RegisterType((*DeleteCertficateRequest)(nil), "certificate.DeleteCertficateRequest")
	proto.RegisterType((*DeleteCertficateResponse)(nil), "certificate.DeleteCertficateResponse")
	proto.RegisterType((*ListCertficateRequest)(nil), "certificate.ListCertficateRequest")
	proto.RegisterType((*ListCertficateResponse)(nil), "certificate.ListCertficateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CertificateService service

type CertificateServiceClient interface {
	Create(ctx context.Context, in *CreateCertficateRequest, opts ...grpc.CallOption) (*CreateCertficateResponse, error)
	Read(ctx context.Context, in *ReadCertficateRequest, opts ...grpc.CallOption) (*ReadCertficateResponse, error)
	Update(ctx context.Context, in *UpdateCertficateRequest, opts ...grpc.CallOption) (*UpdateCertficateResponse, error)
	List(ctx context.Context, in *ListCertficateRequest, opts ...grpc.CallOption) (*ListCertficateResponse, error)
	Delete(ctx context.Context, in *DeleteCertficateRequest, opts ...grpc.CallOption) (*DeleteCertficateResponse, error)
}

type certificateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCertificateServiceClient(cc *grpc.ClientConn) CertificateServiceClient {
	return &certificateServiceClient{cc}
}

func (c *certificateServiceClient) Create(ctx context.Context, in *CreateCertficateRequest, opts ...grpc.CallOption) (*CreateCertficateResponse, error) {
	out := new(CreateCertficateResponse)
	err := grpc.Invoke(ctx, "/certificate.CertificateService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Read(ctx context.Context, in *ReadCertficateRequest, opts ...grpc.CallOption) (*ReadCertficateResponse, error) {
	out := new(ReadCertficateResponse)
	err := grpc.Invoke(ctx, "/certificate.CertificateService/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Update(ctx context.Context, in *UpdateCertficateRequest, opts ...grpc.CallOption) (*UpdateCertficateResponse, error) {
	out := new(UpdateCertficateResponse)
	err := grpc.Invoke(ctx, "/certificate.CertificateService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) List(ctx context.Context, in *ListCertficateRequest, opts ...grpc.CallOption) (*ListCertficateResponse, error) {
	out := new(ListCertficateResponse)
	err := grpc.Invoke(ctx, "/certificate.CertificateService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Delete(ctx context.Context, in *DeleteCertficateRequest, opts ...grpc.CallOption) (*DeleteCertficateResponse, error) {
	out := new(DeleteCertficateResponse)
	err := grpc.Invoke(ctx, "/certificate.CertificateService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CertificateService service

type CertificateServiceServer interface {
	Create(context.Context, *CreateCertficateRequest) (*CreateCertficateResponse, error)
	Read(context.Context, *ReadCertficateRequest) (*ReadCertficateResponse, error)
	Update(context.Context, *UpdateCertficateRequest) (*UpdateCertficateResponse, error)
	List(context.Context, *ListCertficateRequest) (*ListCertficateResponse, error)
	Delete(context.Context, *DeleteCertficateRequest) (*DeleteCertficateResponse, error)
}

func RegisterCertificateServiceServer(s *grpc.Server, srv CertificateServiceServer) {
	s.RegisterService(&_CertificateService_serviceDesc, srv)
}

func _CertificateService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCertficateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certificate.CertificateService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Create(ctx, req.(*CreateCertficateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCertficateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certificate.CertificateService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Read(ctx, req.(*ReadCertficateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCertficateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certificate.CertificateService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Update(ctx, req.(*UpdateCertficateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertficateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certificate.CertificateService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).List(ctx, req.(*ListCertficateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCertficateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certificate.CertificateService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Delete(ctx, req.(*DeleteCertficateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertificateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "certificate.CertificateService",
	HandlerType: (*CertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CertificateService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _CertificateService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CertificateService_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CertificateService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CertificateService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/tcvem/backend/api/certificate.proto",
}

func init() { proto.RegisterFile("github.com/tcvem/backend/api/certificate.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x41, 0x4f, 0xdc, 0x3c,
	0x10, 0x25, 0xcb, 0x12, 0x60, 0xf8, 0xf4, 0xa9, 0xb2, 0x0a, 0x1b, 0x72, 0x29, 0x4a, 0x41, 0xe2,
	0xb2, 0xb1, 0xa0, 0xea, 0xa1, 0x54, 0xaa, 0x0a, 0xb4, 0x07, 0x04, 0x97, 0x6e, 0x5b, 0x21, 0xf5,
	0x52, 0x39, 0xc9, 0x10, 0x2c, 0x92, 0xd8, 0xb5, 0x1d, 0xd4, 0xfe, 0x34, 0xf8, 0x11, 0xfd, 0x07,
	0xfd, 0x2f, 0x55, 0xe2, 0x2c, 0x2c, 0xd9, 0x0d, 0x2b, 0xa1, 0xde, 0x9c, 0xf1, 0x7b, 0x4f, 0x6f,
	0x66, 0x9e, 0x1c, 0x08, 0x53, 0x6e, 0x2e, 0xcb, 0x28, 0x8c, 0x45, 0x4e, 0x4d, 0x7c, 0x8d, 0x39,
	0x8d, 0x58, 0x7c, 0x85, 0x45, 0x42, 0x99, 0xe4, 0x34, 0x46, 0x65, 0xf8, 0x05, 0x8f, 0x99, 0xc1,
	0x50, 0x2a, 0x61, 0x04, 0x59, 0x9b, 0x28, 0xf9, 0x2f, 0x52, 0x21, 0xd2, 0x0c, 0x69, 0x7d, 0x15,
	0x95, 0x17, 0xd4, 0xf0, 0x1c, 0xb5, 0x61, 0xb9, 0xb4, 0x68, 0xff, 0xe3, 0x84, 0x3a, 0x2f, 0x2e,
	0x44, 0x94, 0x89, 0x9f, 0x42, 0x62, 0x41, 0x99, 0xc9, 0x98, 0x1e, 0x32, 0x29, 0x87, 0x46, 0x88,
	0xec, 0x8a, 0x1b, 0xaa, 0x64, 0x4c, 0x15, 0x6a, 0x51, 0xaa, 0x18, 0xef, 0x0e, 0x8d, 0xcc, 0x41,
	0x97, 0x4c, 0x7d, 0x1d, 0x0f, 0x53, 0x2c, 0x86, 0xa9, 0x50, 0x39, 0x15, 0xd2, 0x70, 0x51, 0x68,
	0x5a, 0x7d, 0x58, 0x6e, 0xf0, 0xbb, 0x07, 0x70, 0x8c, 0xca, 0x58, 0xcb, 0xe4, 0x35, 0xf4, 0x78,
	0xe2, 0x39, 0x5b, 0xce, 0xee, 0xda, 0xfe, 0x7a, 0x58, 0xdb, 0x08, 0x95, 0x8c, 0xc3, 0x93, 0x04,
	0x8b, 0xaa, 0x2f, 0x54, 0x47, 0xff, 0xdf, 0xde, 0x6c, 0x02, 0xac, 0x90, 0x7e, 0x59, 0xf2, 0x64,
	0xd7, 0x19, 0xf5, 0x78, 0x42, 0xde, 0x00, 0xc4, 0x0a, 0x99, 0xc1, 0xe4, 0x3b, 0x33, 0x5e, 0xaf,
	0xa6, 0xfb, 0xa1, 0x6d, 0x3f, 0x1c, 0xb7, 0x1f, 0x7e, 0x19, 0xb7, 0x3f, 0x5a, 0x6d, 0xd0, 0x87,
	0xa6, 0xa2, 0x96, 0x32, 0x19, 0x53, 0x17, 0xe7, 0x53, 0x1b, 0xb4, 0xa5, 0x26, 0x98, 0x61, 0x43,
	0xed, 0xcf, 0xa7, 0x36, 0xe8, 0x43, 0x43, 0x08, 0xf4, 0x0b, 0x96, 0xa3, 0xb7, 0xb4, 0xe5, 0xec,
	0xae, 0x8e, 0xea, 0x73, 0x55, 0xbb, 0x14, 0xda, 0x78, 0xae, 0xad, 0x55, 0xe7, 0xaa, 0x26, 0x85,
	0x32, 0xde, 0xb2, 0xad, 0x55, 0x67, 0xf2, 0x1c, 0x96, 0x0a, 0x61, 0x50, 0x7b, 0x2b, 0x75, 0xd1,
	0x7e, 0x1c, 0xb8, 0xb7, 0x37, 0x9b, 0xbd, 0x15, 0x27, 0x38, 0x83, 0xc1, 0x71, 0xdd, 0xdc, 0xfd,
	0x54, 0x47, 0xf8, 0xa3, 0x44, 0x6d, 0xc8, 0x1e, 0x2c, 0x4b, 0xf6, 0x2b, 0x13, 0x6c, 0x3c, 0xe1,
	0x41, 0x38, 0x99, 0xa0, 0x09, 0xc2, 0x18, 0x17, 0x9c, 0x82, 0x37, 0xad, 0xa6, 0xa5, 0x28, 0x34,
	0x12, 0x0a, 0xae, 0x42, 0x5d, 0x66, 0x66, 0x9e, 0x5a, 0x03, 0x0b, 0xde, 0xc1, 0xfa, 0x08, 0x59,
	0x32, 0x6d, 0x6c, 0x67, 0xee, 0xd6, 0xab, 0x2d, 0x07, 0x27, 0xb0, 0xd1, 0xe6, 0x3f, 0xd5, 0xca,
	0x19, 0x0c, 0xbe, 0xd6, 0x7b, 0xfc, 0x57, 0x53, 0x9a, 0x56, 0x7b, 0xaa, 0xb5, 0xf7, 0x30, 0xf8,
	0x50, 0xe7, 0xe4, 0xc9, 0x73, 0xf2, 0xc1, 0x9b, 0x56, 0xb0, 0x76, 0x82, 0x01, 0xac, 0x9f, 0x71,
	0x6d, 0xa6, 0xb4, 0x83, 0x53, 0xd8, 0x68, 0x5f, 0x34, 0x1d, 0xec, 0xc1, 0xb2, 0xb5, 0xa6, 0x3d,
	0x67, 0x6b, 0xf1, 0xd1, 0x81, 0x34, 0xb8, 0xfd, 0x3f, 0x8b, 0x40, 0x8e, 0xef, 0x31, 0x9f, 0x51,
	0x5d, 0xf3, 0x18, 0xc9, 0x39, 0xb8, 0x36, 0x4d, 0x64, 0xfb, 0xa1, 0xc4, 0xec, 0xc0, 0xfa, 0x3b,
	0x73, 0x50, 0x4d, 0x4f, 0x0b, 0xe4, 0x13, 0xf4, 0xab, 0x64, 0x90, 0xe0, 0x01, 0x61, 0x66, 0xd8,
	0xfc, 0x97, 0x8f, 0x62, 0xee, 0x24, 0xcf, 0xc1, 0xb5, 0x3b, 0x6d, 0x79, 0xed, 0x88, 0x4d, 0xcb,
	0x6b, 0x57, 0x1c, 0xac, 0xd7, 0x6a, 0xd0, 0x2d, 0xaf, 0x33, 0x97, 0xd2, 0xf2, 0x3a, 0x7b, 0x3f,
	0xc1, 0x02, 0x49, 0xc1, 0xb5, 0x0b, 0x6f, 0x79, 0xed, 0xc8, 0x51, 0xcb, 0x6b, 0x67, 0x56, 0x9e,
	0xdd, 0xde, 0x6c, 0xfe, 0x37, 0xf9, 0x3c, 0xfb, 0xcd, 0x23, 0x73, 0xb4, 0xfd, 0x2d, 0xe8, 0xfc,
	0x31, 0xc9, 0xab, 0x94, 0xca, 0xe8, 0xad, 0x8c, 0x22, 0xb7, 0x7e, 0x03, 0x5f, 0xfd, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x06, 0x21, 0xb9, 0xe4, 0xc5, 0x06, 0x00, 0x00,
}
