// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tcvem/backend/api/service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/tcvem/backend/api/service.proto
	github.com/tcvem/backend/api/certificate.proto

It has these top-level messages:
	VersionResponse
	Certficate
	CreateCertficateRequest
	CreateCertficateResponse
	ReadCertficateRequest
	ReadCertficateResponse
	UpdateCertficateRequest
	UpdateCertficateResponse
	DeleteCertficateRequest
	DeleteCertficateResponse
	ListCertficateRequest
	ListCertficateResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Backend service

type BackendClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/service.Backend/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Backend service

type BackendServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*VersionResponse, error)
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Backend/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Backend_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/tcvem/backend/api/service.proto",
}

func init() { proto.RegisterFile("github.com/tcvem/backend/api/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xbd, 0xc5, 0x62, 0x16, 0xa1, 0x83, 0x94, 0xea, 0x20, 0xc5, 0x41, 0xd4, 0x4b, 0x40,
	0x37, 0x6f, 0x91, 0x03, 0x71, 0x70, 0xbb, 0xc1, 0xc1, 0x2d, 0xc9, 0xbd, 0xc6, 0x70, 0x6d, 0x5e,
	0x48, 0x72, 0xd5, 0xfe, 0xf7, 0xd2, 0x26, 0x95, 0xa2, 0xde, 0x96, 0xef, 0xbd, 0xf7, 0x7d, 0x1f,
	0xfc, 0x42, 0x6e, 0x94, 0x0e, 0x1f, 0x7b, 0x41, 0x25, 0xb6, 0x2c, 0xc8, 0x0e, 0x5a, 0x26, 0xb8,
	0xdc, 0x81, 0xd9, 0x32, 0x6e, 0x35, 0xf3, 0xe0, 0x3a, 0x2d, 0x81, 0x5a, 0x87, 0x01, 0xf3, 0x2c,
	0xc9, 0xf2, 0x5c, 0x21, 0xaa, 0x06, 0xd8, 0x38, 0x16, 0xfb, 0x9a, 0x41, 0x6b, 0x43, 0x1f, 0xaf,
	0xca, 0x8b, 0xb4, 0x1c, 0xfc, 0xdc, 0x18, 0x0c, 0x3c, 0x68, 0x34, 0x3e, 0x6d, 0x57, 0xb3, 0xbe,
	0xa6, 0xaf, 0x43, 0xcc, 0x90, 0x4b, 0x05, 0x66, 0xd9, 0xf1, 0x46, 0x6f, 0x79, 0x00, 0xf6, 0xe7,
	0x91, 0xcc, 0x77, 0xb3, 0x63, 0xff, 0xc9, 0x95, 0x02, 0xc7, 0xd0, 0x8e, 0xf1, 0xff, 0x54, 0x3d,
	0xce, 0xaa, 0xb4, 0xa9, 0x51, 0x34, 0xf8, 0x85, 0x16, 0xcc, 0xbc, 0x52, 0xa1, 0x6b, 0x7f, 0x22,
	0x06, 0x11, 0xbd, 0xd5, 0x2d, 0x39, 0x7d, 0x03, 0xe7, 0x35, 0x9a, 0x0d, 0x78, 0x8b, 0xc6, 0x43,
	0x5e, 0x90, 0xac, 0x8b, 0xa3, 0x62, 0x71, 0xb9, 0xb8, 0x3e, 0xd9, 0x4c, 0xf2, 0xfe, 0x95, 0x64,
	0xeb, 0x08, 0x2d, 0x7f, 0x22, 0xe4, 0x05, 0x42, 0xb2, 0xe6, 0x67, 0x34, 0xb2, 0xa0, 0x13, 0x28,
	0xfa, 0x3c, 0x80, 0x2a, 0x0b, 0x3a, 0x81, 0xfd, 0x55, 0x52, 0x1d, 0xad, 0xaf, 0xde, 0xab, 0x83,
	0x5f, 0x62, 0x77, 0x8a, 0x59, 0xb1, 0xb2, 0x42, 0x1c, 0x8f, 0x89, 0x0f, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x16, 0x55, 0x83, 0xbf, 0x01, 0x00, 0x00,
}
