// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/tcvem/backend/api/service.proto

// Generated with protoc-gen-gorm version: v0.17.0
// Anticipating compatibility with atlas-app-toolkit version: v0.18.0

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	github.com/tcvem/backend/api/service.proto
	github.com/tcvem/backend/api/certificate.proto

It has these top-level messages:
	VersionResponse
	Certficate
	CreateCertficateRequest
	CreateCertficateResponse
	ReadCertficateRequest
	ReadCertficateResponse
	UpdateCertficateRequest
	UpdateCertficateResponse
	DeleteCertficateRequest
	DeleteCertficateResponse
	ListCertficateRequest
	ListCertficateResponse
*/
package pb

import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf
